'use strict';
const COLORS = Object.freeze(['Red','Blue','Green','Yellow']);
const CHARACTERS = Object.freeze(['Bug','Face','Ling Ling','Beanz','The One','Boone','Chicken Joe','Juby','Meemaw']);
const MIN_PLAYERS=2, MAX_PLAYERS=6, STARTING_HAND=8, STARTING_POINTS=500;
const SPECIAL_POINTS=Object.freeze({SKIP:100,REVERSE:100,WILD:200,PLAY_YOUR_HAND:300});
function buildDeck(){const deck=[];for(const character of CHARACTERS) for(const color of COLORS) for(let copy=0;copy<2;copy++) deck.push({id:`${color}-${character}-${copy}`,type:'CHARACTER',color,character});for(let i=0;i<8;i++) deck.push({id:`SKIP-${i}`,type:'SKIP',color:COLORS[i%4]});for(let i=0;i<8;i++) deck.push({id:`REVERSE-${i}`,type:'REVERSE',color:COLORS[i%4]});for(let i=0;i<8;i++) deck.push({id:`WILD-${i}`,type:'WILD',color:null});for(let i=0;i<12;i++) deck.push({id:`PLAY-${i}`,type:'PLAY_YOUR_HAND',color:null});if(deck.length!==108)throw new Error('Deck must contain exactly 108 cards');return deck}
function shuffle(a,rng=Math.random){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function topCard(g){return g.discard[g.discard.length-1]}
function currentColor(g){return g.currentColor||topCard(g)?.color||null}
function currentPlayer(g){return g.players[g.turnIndex]}
function isPlayable(card,g){if(card.type==='PLAY_YOUR_HAND'||card.type==='WILD')return true;const top=topCard(g),color=currentColor(g);return card.color===color||(card.type==='CHARACTER'&&top?.character===card.character)}
function refill(g){if(g.deck.length)return;if(g.discard.length<=1)throw new Error('No cards available to draw');const top=g.discard.pop();g.deck=shuffle(g.discard);g.discard=[top]}
function drawCard(g,playerId){const p=currentPlayer(g);if(p.id!==playerId)throw new Error('Not your turn');if(g.pending)throw new Error('Finish the current action first');return drawUntilPlayable(g,p)}
function drawUntilPlayable(g,p){let drawn=0;while(true){refill(g);const c=g.deck.shift();p.hand.push(c);drawn++;if(isPlayable(c,g))return{drawn,card:c}}}
function advance(g,steps=1){g.turnIndex=(g.turnIndex+g.direction*steps+g.players.length*100)%g.players.length}
function startTurn(g){const p=currentPlayer(g);const playable=p.hand.some(c=>isPlayable(c,g));return{player:p,playable}}
function createGame({playerIds,rng=Math.random}){if(!Array.isArray(playerIds)||playerIds.length<MIN_PLAYERS||playerIds.length>MAX_PLAYERS)throw new Error(`Players must be ${MIN_PLAYERS}-${MAX_PLAYERS}`);let deck=shuffle(buildDeck(),rng),players=playerIds.map(id=>({id,hand:[],points:STARTING_POINTS,shield:false,extraPlay:false,colorChoice:false,turnSwitch:false,connected:true}));for(const p of players)p.hand=deck.splice(0,STARTING_HAND);let first;do{first=deck.shift();deck.push(first)}while(first.type==='PLAY_YOUR_HAND');const g={phase:'playing',round:1,players,deck,discard:[first],turnIndex:0,direction:1,currentColor:first.color||null,pending:null,wheelResult:null,winner:null};startTurn(g);return g}
function finishRoundOrGame(g,playerId){g.pending=null;g.roundWinnerId=playerId;const p=g.players.find(x=>x.id===playerId);if(p&&g.finalCardBonusAwarded!==playerId){p.points+=500;g.finalCardBonusAwarded=playerId}if(g.round===2){g.phase='finished';g.winner=[...g.players].sort((a,b)=>b.points-a.points)[0].id}else g.phase='round_complete'}
function playCard(g,playerId,cardId,extra={}){const p=currentPlayer(g);if(p.id!==playerId)throw new Error('Not your turn');if(g.pending)throw new Error('Finish the current action first');const idx=p.hand.findIndex(c=>c.id===cardId);if(idx<0)throw new Error('Card not in hand');const card=p.hand[idx];if(!isPlayable(card,g))throw new Error('Card is not playable');p.hand.splice(idx,1);g.discard.push(card);g.currentColor=card.color||g.currentColor;g.pending=null;
if(SPECIAL_POINTS[card.type])p.points+=SPECIAL_POINTS[card.type];
if(p.hand.length===0){p.points+=500;g.finalCardBonusAwarded=playerId}let turnAlreadyAdvanced=false;if(card.type==='SKIP'){advance(g);const target=currentPlayer(g);if(target.shield){target.shield=false;advance(g)}else advance(g);turnAlreadyAdvanced=true}else if(card.type==='REVERSE'){g.direction*=-1;if(g.players.length===2){advance(g,2);turnAlreadyAdvanced=true}}else if(card.type==='WILD'){g.pending={type:'WILD_COLOR_CHOICE',playerId}}else if(card.type==='PLAY_YOUR_HAND'){g.pending={type:'SPIN_WHEEL',playerId}}if(p.hand.length===0&&card.type!=='WILD'){finishRoundOrGame(g,playerId);return card}if(g.pending?.type!=='SPIN_WHEEL'&&g.pending?.type!=='WILD_COLOR_CHOICE'){if(p.extraPlay)p.extraPlay=false;else if(!turnAlreadyAdvanced)advance(g);if(g.phase==='playing')startTurn(g)}return card}
function chooseWildColor(g,playerId,color){if(g.pending?.type!=='WILD_COLOR_CHOICE'||g.pending.playerId!==playerId)throw new Error('Wild color choice is not pending');if(!COLORS.includes(color))throw new Error('Color required');g.currentColor=color;const p=g.players.find(x=>x.id===playerId);if(p?.hand.length===0){finishRoundOrGame(g,playerId);return color}g.pending=null;advance(g);if(g.phase==='playing')startTurn(g);return color}
function spinWheel(g,playerId,rng=Math.random){if(g.pending?.type!=='SPIN_WHEEL'||g.pending.playerId!==playerId)throw new Error('Wheel is not pending');const index=Math.floor(rng()*9),powers=['EXTRA_PLAY','SHIELD','COLOR_CHOICE','EXTRA_PLAY','TURN_SWITCH','SHIELD','COLOR_CHOICE','EXTRA_PLAY','TURN_SWITCH'],power=powers[index],p=currentPlayer(g);p[camel(power)]=true;g.wheelResult={section:index+1,power};g.pending={type:'POWER_USED',power,playerId};return g.wheelResult}
function usePower(g,playerId,power,data={}){const p=g.players.find(x=>x.id===playerId);if(!p||currentPlayer(g).id!==playerId)throw new Error('Not your turn');if(!['EXTRA_PLAY','SHIELD','COLOR_CHOICE','TURN_SWITCH'].includes(power))throw new Error('Unknown power');const key=camel(power);if(!p[key])throw new Error('Power not available');p[key]=false;if(power==='COLOR_CHOICE'){if(!COLORS.includes(data.color))throw new Error('Color required');g.currentColor=data.color}if(power==='TURN_SWITCH')g.direction*=-1;if(power==='EXTRA_PLAY')p.extraPlay=true;if(power==='SHIELD')p.shield=true;g.pending=null;if(power==='EXTRA_PLAY')startTurn(g);else{advance(g);if(g.phase==='playing')startTurn(g)}return power}
function camel(x){return x.toLowerCase().replace(/_([a-z])/g,(_,c)=>c.toUpperCase())}
function completeRound(g){if(g.phase!=='round_complete')throw new Error('Round is not complete');if(g.round===2){g.phase='finished';g.winner=[...g.players].sort((a,b)=>b.points-a.points)[0].id;return}g.round=2;g.phase='playing';g.deck=shuffle(buildDeck());g.discard=[];g.currentColor=null;g.pending=null;g.wheelResult=null;g.turnIndex=0;g.direction=1;for(const p of g.players){p.hand=[];p.shield=false;p.extraPlay=false;p.colorChoice=false;p.turnSwitch=false}for(const p of g.players)p.hand=g.deck.splice(0,STARTING_HAND);let first;do{first=g.deck.shift();g.deck.push(first)}while(first.type==='PLAY_YOUR_HAND');g.discard=[first];g.currentColor=first.color||null;startTurn(g)}
module.exports={COLORS,CHARACTERS,MIN_PLAYERS,MAX_PLAYERS,STARTING_HAND,STARTING_POINTS,SPECIAL_POINTS,buildDeck,shuffle,createGame,isPlayable,startTurn,playCard,chooseWildColor,spinWheel,usePower,completeRound,currentPlayer,currentColor,topCard,drawUntilPlayable,drawCard};