const http=require('http'),fs=require('fs'),path=require('path'),{WebSocketServer}=require('ws');
const PORT=process.env.PORT||10000,HOST='0.0.0.0',rooms=new Map(),COLORS=['red','blue','green','yellow'],CHARS=['Bug','Face','Ling Ling','Beanz','The One','Boone','Chicken Joe','Juby','Meemaw'];
const HOST_GRACE_MS=10*60*1000;
const WHEEL=[['Bug','EXTRA PLAY','Royal Blue'],['Face','SHIELD','Deep Purple'],['Ling Ling','COLOR CHOICE','Emerald'],['Beanz','EXTRA PLAY','Gold'],['The One','TURN SWITCH','Royal Blue'],['Boone','SHIELD','Emerald'],['Chicken Joe','COLOR CHOICE','Deep Purple'],['Juby','EXTRA PLAY','Gold'],['Meemaw','TURN SWITCH','Royal Blue']];
const send=(w,o)=>w&&w.readyState===1&&w.send(JSON.stringify(o));
const shuffle=a=>{for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const token=()=>Math.random().toString(36).slice(2)+Date.now().toString(36),pid=()=>Math.random().toString(36).slice(2,12);
function deck(){let d=[];for(const color of COLORS)for(const ch of CHARS)for(let i=0;i<2;i++)d.push({color,ch});for(const color of COLORS)for(const action of ['SKIP','REVERSE'])for(let i=0;i<2;i++)d.push({color,action});for(let i=0;i<8;i++)d.push({color:'wild',action:'WILD'});for(let i=0;i<12;i++)d.push({color:null,action:'BET'});return shuffle(d)}
const top=r=>r.discard[r.discard.length-1],current=r=>r.players.find(p=>p.id===r.turnPlayerId)||r.players[r.turn];
function feature(r){return true}
function playable(r,c){let t=top(r);if(!t)return true;if(c.action==='WILD')return true;if(c.action==='BET')return true;let col=r.pendingColor||t.color;return c.color===col||(c.ch&&t.ch&&c.ch===t.ch)}
function hasMatch(r,p){return p.hand.some(c=>playable(r,c))}
function colorOrChar(r,p){let t=top(r),col=r.pendingColor||t?.color;return !t||p.hand.some(c=>(c.color&&c.color===col)||(c.ch&&t.ch&&c.ch===t.ch))}
function pub(r){return{phase:r.phase,round:r.round,turn:r.turn,turnPlayerId:r.turnPlayerId,direction:r.direction,discard:r.discard,featureUnlocked:true,completedTurns:r.completed.size,players:r.players.map(p=>({id:p.id,name:p.name,character:p.character,points:p.points,handCount:p.hand.length,power:p.power||null,connected:!!p.ws})),pending:r.pending,activeColor:r.pendingColor||null,winner:r.winner||null}}
function log(r,s){r.log.unshift(s);if(r.log.length>80)r.log.pop();for(const p of r.players)send(p.ws,{type:'log',text:s});send(r.host,{type:'log',text:s})}
function broadcast(r){send(r.host,{type:'state',state:pub(r),log:r.log});for(const p of r.players)send(p.ws,{type:'state',state:pub(r),hand:p.hand,me:p.id,log:r.log})}
function refill(r){if(r.discard.length<2)return false;let keep=r.discard.pop();r.deck=shuffle(r.discard.splice(0));r.discard=[keep];return true}
function drawOne(r,p){if(!r.deck.length&&!refill(r))return null;let c=r.deck.pop();if(c)p.hand.push(c);return c}
function award(r){let p=current(r);if(!p||r.phase!=='playing'||r.pending||r.awarded===r.turnSerial)return;if(p.hand.some(c=>playable(r,c))){p.points+=150;r.awarded=r.turnSerial;log(r,`${p.name} earned +150 for starting with a playable card.`)}}
function advance(r,steps=1){let from=current(r);if(!from)return;let n=r.players.length,idx=r.players.indexOf(from),ti=(idx+r.direction*steps+n*100)%n;if(steps===2&&r.players[ti]?.shield){let b=r.players[ti];b.shield=0;b.power=null;log(r,`${b.name} used SHIELD to block the Skip.`);ti=(idx+r.direction+n*100)%n}r.turn=ti;r.turnPlayerId=r.players[ti].id;r.turnSerial++;r.awarded=-1;log(r,`TURN: ${from.name} -> ${r.players[ti].name}.`);award(r)}
function deal(r){r.deck=deck();r.discard=[];r.pending=null;r.pendingColor=null;r.direction=1;r.completed=new Set();let i=Math.floor(Math.random()*r.players.length);r.turn=i;r.turnPlayerId=r.players[i].id;r.turnSerial++;r.awarded=-1;r.winner=null;for(const p of r.players){p.hand=[];p.power=null;p.shield=0;p.extraPlay=0;p.lastCardBonus=null;for(let n=0;n<8;n++)drawOne(r,p)}let first=r.deck.pop();while(first&&(first.action==='BET'||first.action==='WILD')){r.deck.unshift(first);first=r.deck.pop()}r.discard.push(first)}
function start(r){if(r.players.length<2||r.players.length>6)return false;r.phase='playing';r.round=1;deal(r);log(r,`Round 1 started with ${r.players.length} players.`);award(r);broadcast(r);return true}
function start2(r){r.phase='playing';r.round=2;deal(r);log(r,'Round 2 started. Round 1 points carry forward.');award(r);broadcast(r)}
function finish(r,w){r.phase='roundover';r.winner=w.name;r.pending=null;r.pendingColor=null;log(r,`${w.name} won Round ${r.round}.`);broadcast(r);if(r.round===1)setTimeout(()=>rooms.has(r.code)&&start2(r),2500);else{r.phase='finished';r.winner=[...r.players].sort((a,b)=>b.points-a.points)[0].name;log(r,`MATCH OVER — ${r.winner} wins.`);broadcast(r)}}
function play(r,p,i){if(r.phase!=='playing'||r.pending)return send(p.ws,{type:'toast',text:'Finish the current action first.'});if(current(r)?.id!==p.id)return send(p.ws,{type:'toast',text:'It is not your turn.'});let c=p.hand[i];if(!c||!playable(r,c))return send(p.ws,{type:'toast',text:'That card cannot be played.'});let extra=!!p.extraPlay;p.hand.splice(i,1);r.discard.push(c);log(r,`${p.name} played ${c.action==='BET'?'BET YOUR HAND':c.action||c.ch}.`);if(p.hand.length===1&&!p.lastCardBonus){p.lastCardBonus=250;p.points+=250;log(r,`${p.name} reached LAST CARD and earned +250.`)}if(!p.hand.length)return finish(r,p);if(c.action==='WILD'){p.extraPlay=0;r.pending={type:'color',playerId:p.id,playerName:p.name,power:extra?'EXTRA PLAY':null};broadcast(r);return}if(c.action==='BET'){p.extraPlay=0;r.pending={type:'wheel',playerId:p.id,playerName:p.name,wheel:null,wheelColor:null,power:null};broadcast(r);setTimeout(()=>wheel(r.code),2200);return}if(extra){p.extraPlay=0;p.power=null;broadcast(r);return}r.pendingColor=null;let steps=c.action==='SKIP'?2:1;if(c.action==='REVERSE'){r.direction*=-1;if(r.players.length===2)steps=2}advance(r,steps);broadcast(r)}
function wheel(code){let r=rooms.get(code);if(!r?.pending||r.pending.type!=='wheel')return;let p=r.players.find(x=>x.id===r.pending.playerId);if(!p)return;let w=WHEEL[Math.floor(Math.random()*WHEEL.length)];r.pending={type:'wheel',playerId:p.id,playerName:p.name,wheel:w[0],wheelColor:w[2],power:w[1]};log(r,`${p.name}'s Power Wheel landed on ${w[0]}: ${w[1]}.`);broadcast(r);setTimeout(()=>{let x=rooms.get(code);if(!x?.pending||x.pending.type!=='wheel')return;let q=x.players.find(z=>z.id===x.pending.playerId),power=x.pending.power;if(!q)return;x.pending=null;if(power==='EXTRA PLAY'){q.extraPlay=1;q.power=power;log(x,`${q.name} received EXTRA PLAY.`);broadcast(x);return}if(power==='SHIELD'){q.shield=1;q.power=power;advance(x);broadcast(x);return}if(power==='TURN SWITCH'){x.direction*=-1;q.power=null;log(x,`${q.name} used TURN SWITCH.`);advance(x);broadcast(x);return}if(power==='COLOR CHOICE'){q.power=power;x.pending={type:'color',playerId:q.id,playerName:q.name,power};broadcast(x);return}advance(x);broadcast(x)},1800)}
function chooseColor(r,p,c){if(!r.pending||r.pending.type!=='color'||r.pending.playerId!==p.id||!COLORS.includes(c))return send(p.ws,{type:'toast',text:'Choose a valid color.'});r.pendingColor=c;let extra=p.extraPlay,cp=r.pending.power==='COLOR CHOICE';r.pending=null;if(cp)p.power=null;if(extra){p.extraPlay=0;p.power=null;broadcast(r);return}advance(r);broadcast(r)}
function draw(r,p){if(r.phase!=='playing'||r.pending)return send(p.ws,{type:'toast',text:'Finish the current action first.'});if(current(r)?.id!==p.id)return send(p.ws,{type:'toast',text:'It is not your turn.'});if(colorOrChar(r,p))return send(p.ws,{type:'toast',text:'You have a matching color or character.'});p.lastCardBonus=null;let n=0;while(!colorOrChar(r,p)&&n<108){if(!drawOne(r,p))break;n++}log(r,`${p.name} drew ${n} card${n===1?'':'s'} until a color or character match was found.`);broadcast(r)}
function restart(r){r.phase='lobby';r.round=1;r.turn=0;r.turnPlayerId=null;r.direction=1;r.turnSerial=0;r.awarded=-1;r.deck=[];r.discard=[];r.pending=null;r.pendingColor=null;r.winner=null;r.completed=new Set();for(const p of r.players){p.points=500;p.hand=[];p.power=null;p.shield=0;p.extraPlay=0;p.lastCardBonus=null}log(r,'HOST RESTARTED THE GAME. Players were returned to the lobby.');broadcast(r)}
function newRoom(){let c;do c=String(Math.floor(1000+Math.random()*9000));while(rooms.has(c));return c}
function create(ws,name){let code=newRoom(),t=token(),r={code,hostToken:t,host:ws,hostTimer:null,phase:'lobby',round:1,turn:0,turnPlayerId:null,direction:1,turnSerial:0,awarded:-1,players:[],deck:[],discard:[],pending:null,pendingColor:null,winner:null,log:[],completed:new Set()};ws.role='host';ws.roomCode=code;ws.resumeToken=t;rooms.set(code,r);send(ws,{type:'hostRoom',code,token:t,state:pub(r)});log(r,`Room ${code} created.`);broadcast(r)}
function join(ws,code,name,ch){let r=rooms.get(code);if(!r)return send(ws,{type:'error',text:'ROOM NOT FOUND. Make sure the host is still connected.'});if(r.phase!=='lobby')return send(ws,{type:'error',text:'This game has already started.'});if(r.players.length>=6)return send(ws,{type:'error',text:'Room is full. Maximum 6 players.'});if(!CHARS.includes(ch))return send(ws,{type:'error',text:'Choose a character first.'});if(r.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return send(ws,{type:'error',text:'That player name is already in use.'});if(r.players.some(p=>p.character===ch))return send(ws,{type:'error',text:'That character is already taken.'});let p={id:pid(),token:token(),name:name||'Player',character:ch,points:500,hand:[],ws,lastCardBonus:null,power:null,shield:0,extraPlay:0};r.players.push(p);ws.role='player';ws.roomCode=code;ws.playerId=p.id;ws.resumeToken=p.token;send(ws,{type:'welcome',id:p.id,token:p.token,state:pub(r),hand:p.hand});log(r,`${p.name} joined the game.`);broadcast(r)}
function resumeHost(ws,c,t){let r=rooms.get(c);if(!r||r.hostToken!==t)return send(ws,{type:'error',text:'HOST SESSION EXPIRED. Create a new room.'});if(r.hostTimer)clearTimeout(r.hostTimer);r.host=ws;ws.role='host';ws.roomCode=c;ws.resumeToken=t;send(ws,{type:'hostResumed',code:c,token:t,state:pub(r),log:r.log});broadcast(r)}
function resumePlayer(ws,c,t){let r=rooms.get(c),p=r?.players.find(x=>x.token===t);if(!r)return send(ws,{type:'error',text:'ROOM SESSION EXPIRED.'});if(!p)return send(ws,{type:'error',text:'PLAYER SESSION EXPIRED. Join the room again.'});p.ws=ws;ws.role='player';ws.roomCode=c;ws.playerId=p.id;ws.resumeToken=t;send(ws,{type:'playerResumed',id:p.id,token:t,state:pub(r),hand:p.hand,log:r.log});broadcast(r)}
function handle(ws,m){if(m?.type==='create'&&!ws.role)return create(ws,String(m.name||'Host').trim().slice(0,16));if(m?.type==='join'&&!ws.role)return join(ws,String(m.code||'').replace(/\D/g,'').slice(0,4),String(m.name||'Player').trim().slice(0,16),String(m.character||''));if(m?.type==='resumeHost'&&!ws.role)return resumeHost(ws,String(m.code||''),String(m.token||''));if(m?.type==='resumePlayer'&&!ws.role)return resumePlayer(ws,String(m.code||''),String(m.token||''));let r=rooms.get(ws.roomCode);if(!r)return send(ws,{type:'error',text:'Not connected to a room.'});if(m.type==='sync')return ws.role==='host'?send(ws,{type:'state',state:pub(r),log:r.log}):broadcast(r);if(ws.role==='host'&&m.type==='start'){if(!start(r))send(ws,{type:'toast',text:`Need 2–6 players to start. ${r.players.length}/6 joined.`);return}if(ws.role==='host'&&m.type==='restart'){restart(r);return}if(ws.role!=='player')return;let p=r.players.find(x=>x.id===ws.playerId);if(!p)return;if(m.type==='call'){let a=current(r);if(a&&a.id!==p.id&&!r.pending){send(a.ws,{type:'toast',text:p.name+' is calling you to play.'});log(r,`${p.name} called ${a.name} to play.`)}return}if(m.type==='play')play(r,p,Number(m.index));else if(m.type==='draw')draw(r,p);else if(m.type==='color')chooseColor(r,p,m.color)}
function disconnect(ws){let r=rooms.get(ws.roomCode);if(!r)return;if(ws.role==='host'){if(r.host!==ws)return;r.host=null;clearTimeout(r.hostTimer);r.hostTimer=setTimeout(()=>{if(rooms.has(r.code)&&!r.host)rooms.delete(r.code)},HOST_GRACE_MS);return}let p=r.players.find(x=>x.id===ws.playerId);if(p&&p.ws===ws){p.ws=null;send(r.host,{type:'playerDisconnected',playerId:p.id,name:p.name})}}
const CLIENT_PATCH=`<script>(function(){function sync(){if(typeof state==='undefined'||!state)return;var p=state.pending;['betPanel','challengePanel','colorPanel','wheelPanel','lastCardPanel'].forEach(function(id){var e=document.getElementById(id);if(e)e.classList.add('hidden')});if(p&&p.type==='color'&&mode==='player'&&myId===p.playerId){var e=document.getElementById('colorPanel');if(e)e.classList.remove('hidden')}if(p&&p.type==='wheel'){var e=document.getElementById('wheelPanel');if(e){var w=document.getElementById('wheelText');if(w)w.textContent=p.playerName+' • '+(p.wheel||'SPINNING')+(p.power?' • '+p.power:'');e.classList.remove('hidden')}}if(typeof window.myHand!=='undefined'&&mode==='player'){var h=window.myHand,turn=state.players&&state.players[state.turn]&&state.players[state.turn].id===myId;document.querySelectorAll('#myHand button').forEach(function(b,i){var c=h[i],top=state.discard&&state.discard[state.discard.length-1],col=state.activeColor||(top&&top.color),ok=c&&(c.action==='BET'||c.action==='WILD'||(top&&((c.color&&c.color===col)||(c.ch&&top.ch&&c.ch===top.ch))));b.disabled=!turn||!ok||!!state.pending||state.phase!=='playing'});var d=document.getElementById('drawBtn');if(d)d.disabled=!turn||h.some(function(c){var top=state.discard&&state.discard[state.discard.length-1],col=state.activeColor||(top&&top.color);return c&&(c.color===col||(c.ch&&top&&c.ch===top.ch))})||!!state.pending||state.phase!=='playing'}}function tick(){sync();if(typeof ws!=='undefined'&&ws&&ws.readyState===1)send({type:'sync'})}setInterval(tick,1000);window.addEventListener('load',tick)})();</script>`;
const server=http.createServer((req,res)=>{let f=(req.url.split('?')[0]==='/')?'/index.html':req.url.split('?')[0],fp=path.join(__dirname,path.normalize(f));if(!fp.startsWith(__dirname))return res.end('Bad path');fs.readFile(fp,(e,d)=>{if(e){res.writeHead(404);return res.end('Not found')}let body=path.extname(fp)==='.html'?Buffer.from(d.toString().replace('</body>',CLIENT_PATCH+'</body>')):d;let ext=path.extname(fp);res.writeHead(200,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript':ext==='.css'?'text/css':'application/octet-stream','Cache-Control':'no-store'});res.end(body)})});
const wss=new WebSocketServer({server});wss.on('connection',ws=>{ws.role=null;ws.isAlive=true;ws.on('pong',()=>{ws.isAlive=true});ws.on('message',raw=>{try{handle(ws,JSON.parse(raw))}catch(e){console.error(e);send(ws,{type:'error',text:'Server error. Please refresh and try again.'})}});ws.on('close',()=>disconnect(ws));
const heartbeat=setInterval(()=>{wss.clients.forEach(ws=>{if(ws.isAlive===false)return ws.terminate();ws.isAlive=false;try{ws.ping()}catch(e){try{ws.terminate()}catch(_){}}})},20000);wss.on('close',()=>clearInterval(heartbeat));
server.listen(PORT,HOST,()=>console.log(`BET YOUR HAND server on ${HOST}:${PORT}`));