(() => {
'use strict';
const SEAT_IMAGES={'Bug':'/bug-seat.png?v=1','Face':'/face-seat.png?v=1','Ling Ling':'/ling-ling-seat.png?v=1','Beanz':'/beanz-seat.png?v=1','The One':'/the-one-seat.png?v=1','Boone':'/boone-seat.png?v=1','Chicken Joe':'/chicken-joe-seat.png?v=1','Juby':'/juby-seat.png?v=1','Meemaw':'/meemaw-seat.png?v=1'};
let pendingFinishData=null,audioCtx=null,audioBufferPromise=null,audioSource=null;
function preloadFinishAudio(){if(audioBufferPromise)return audioBufferPromise;try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch{return Promise.resolve(null)}audioBufferPromise=fetch('/assets/finish-screen.mp3',{cache:'force-cache'}).then(r=>r.arrayBuffer()).then(b=>audioCtx.decodeAudioData(b)).catch(()=>null);return audioBufferPromise}
function unlockAudio(){try{if(audioCtx&&audioCtx.state==='suspended')return audioCtx.resume().catch(()=>{})}catch{}return Promise.resolve()}
function stopAllFinishAudio(){try{if(audioSource){audioSource.stop();audioSource.disconnect()}}catch{}audioSource=null;document.querySelectorAll('audio').forEach(a=>{try{if(String(a.currentSrc||a.src||'').includes('finish-screen.mp3')){a.pause();a.currentTime=0}}catch{}})}
function fallbackAudio(startAt,clockOffset){const a=document.getElementById('host-finish-music');if(!a)return;const wait=Math.max(0,Number(startAt||0)-(Date.now()+Number(clockOffset||0)));setTimeout(()=>{if(!document.body.contains(a))return;a.currentTime=0;a.play().catch(()=>{})},wait)}
function scheduleHostMusic(startAt,clockOffset){stopAllFinishAudio();const targetMs=Number(startAt||0)-Number(clockOffset||0);preloadFinishAudio().then(buffer=>unlockAudio().then(()=>{if(!buffer||!audioCtx){fallbackAudio(startAt,clockOffset);return}const delta=(targetMs-Date.now())/1000;const source=audioCtx.createBufferSource();source.buffer=buffer;source.connect(audioCtx.destination);source.start(audioCtx.currentTime+Math.max(0,delta),Math.max(0,-delta));audioSource=source})).catch(()=>fallbackAudio(startAt,clockOffset))}
function installFinishStyles(){if(document.getElementById('host-finish-test-styles'))return;const style=document.createElement('style');style.id='host-finish-test-styles';style.textContent=`#host-finish-test-overlay{position:fixed;inset:0;z-index:100000;background:#05020d;color:#fff;overflow:hidden;display:flex;align-items:center;justify-content:center;font-family:system-ui,sans-serif}.host-finish-test-bg{position:absolute;inset:0;background:url('/finish-screen.png?v=1') center/100% 100% no-repeat}#host-test-winner-slot{position:absolute;left:47.5%;top:51.5%;transform:translate(-50%,-50%);width:clamp(130px,20vw,250px);height:clamp(190px,32vw,360px);display:flex;flex-direction:column;align-items:center;justify-content:flex-start;pointer-events:none}#host-test-winner-score{position:absolute;left:50%;top:-6vh;transform:translateX(-50%);font-size:clamp(28px,5vw,58px);font-weight:1000;color:#fff;text-shadow:0 0 8px #000,0 0 18px #1687ff;margin:0;line-height:1;white-space:nowrap;z-index:3}#host-test-winner-character{width:100%;height:100%;object-fit:contain;object-position:center bottom;filter:drop-shadow(0 8px 8px #000)}#host-finish-host-walker{position:absolute;left:-18%;bottom:11vh;width:clamp(200px,30vw,380px);height:auto;z-index:2;pointer-events:none;animation:hostFinishWalk 18s linear infinite;will-change:left,transform}#host-finish-host-walker img{display:block;width:100%;height:auto;object-fit:contain;filter:drop-shadow(0 8px 8px #000);animation:hostFinishWalkBob 1.05s ease-in-out infinite}@keyframes hostFinishWalk{0%{left:-18%;transform:scaleX(1)}49%{left:103%;transform:scaleX(1)}50%{left:103%;transform:scaleX(-1)}99%{left:-18%;transform:scaleX(-1)}100%{left:-18%;transform:scaleX(1)}}@keyframes hostFinishWalkBob{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}#host-finish-back{position:absolute;z-index:3;left:50%;bottom:5vh;transform:translateX(-50%);width:min(360px,86vw);padding:13px 20px;border:3px solid #fff;border-radius:14px;background:#0869ff;color:#fff;font:1000 clamp(17px,2.8vw,25px)/1 system-ui,sans-serif;box-shadow:0 0 18px #1687ff,0 7px 16px #0009;text-shadow:2px 2px 0 #000;cursor:pointer;display:block}#host-finish-back:active{transform:translateX(-50%) scale(.98)}`;document.head.appendChild(style)}
function updateWinner(data){const character=SEAT_IMAGES[data?.winnerCharacter]?data.winnerCharacter:'Bug';const score=Number.isFinite(Number(data?.winnerScore))?Number(data.winnerScore):500;const img=document.getElementById('host-test-winner-character');const scoreEl=document.getElementById('host-test-winner-score');if(img){img.src=SEAT_IMAGES[character];img.alt=character+' seated winner'}if(scoreEl)scoreEl.textContent=String(score)}
function signalPlayersForTestFinish(){let hostSession=null;try{hostSession=JSON.parse(localStorage.getItem('pyhHostSession')||'null')}catch{}if(!hostSession?.code||!hostSession?.hostId||!hostSession?.hostToken)return;const proto=location.protocol==='https:'?'wss:':'ws:';const testWs=new WebSocket(proto+'//'+location.host);let reconnected=false,done=false;testWs.onopen=()=>testWs.send(JSON.stringify({type:'RECONNECT',code:hostSession.code,hostId:hostSession.hostId,reconnectToken:hostSession.hostToken}));testWs.onmessage=event=>{try{const m=JSON.parse(event.data);if(m.type==='RECONNECTED'&&!reconnected){reconnected=true;testWs.send(JSON.stringify({type:'TEST_FINISH_SCREEN'}));return}if(m.type==='TEST_FINISH_SCHEDULED'&&reconnected&&!done){done=true;pendingFinishData=m;showFinish(m);try{testWs.close()}catch{}return}}catch{}};testWs.onerror=()=>{};setTimeout(()=>{if(!done)try{testWs.close()}catch{}},7000)}
function showFinish(data){const old=document.getElementById('host-finish-test-overlay');if(old)old.remove();stopAllFinishAudio();installFinishStyles();const character=SEAT_IMAGES[data?.winnerCharacter]?data.winnerCharacter:'Bug';const score=Number.isFinite(Number(data?.winnerScore))?Number(data.winnerScore):500;const overlay=document.createElement('div');overlay.id='host-finish-test-overlay';overlay.innerHTML=`<div class="host-finish-test-bg"></div><audio id="host-finish-music" src="/assets/finish-screen.mp3" preload="auto"></audio><div id="host-finish-host-walker" aria-hidden="true"><img src="/host-winner.png?v=1" alt="Host walking with trophy"></div><div id="host-test-winner-slot" aria-label="Test winner seat"><div id="host-test-winner-score">${score}</div><img id="host-test-winner-character" src="${SEAT_IMAGES[character]}" alt="${character} seated winner"></div><button id="host-finish-back" type="button">PLAY AGAIN</button>`;document.body.appendChild(overlay);document.body.classList.add('host-finished');const menuButton=document.getElementById('host-menu-button');if(menuButton)menuButton.style.display='none';preloadFinishAudio();const t0=Date.now();const clockOffset=Number(data?.serverNow)?Number(data.serverNow)-t0:0;scheduleHostMusic(Number(data?.startAt),clockOffset);document.getElementById('host-finish-back')?.addEventListener('click',hideFinish)}
function hideFinish(){stopAllFinishAudio();document.getElementById('host-finish-test-overlay')?.remove();document.body.classList.remove('host-finished');const menuButton=document.getElementById('host-menu-button');if(menuButton)menuButton.style.display='flex';pendingFinishData=null}
function attach(){const button=document.getElementById('host-test-finish');if(!button){setTimeout(attach,250);return}if(button.dataset.finishBound==='1')return;button.dataset.finishBound='1';button.addEventListener('click',()=>{document.getElementById('host-menu-panel')?.classList.remove('show');pendingFinishData=null;preloadFinishAudio();unlockAudio();signalPlayersForTestFinish()})}
window.addEventListener('pointerdown',unlockAudio,{passive:true});window.addEventListener('keydown',unlockAudio,{passive:true});preloadFinishAudio();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',attach,{once:true});else attach();
})();
