'use strict';
const assert=require('node:assert/strict');const test=require('node:test');const engine=require('../engine/card-engine');const{RoomServer}=require('./room-server');const{executeGameAction}=require('./game-actions');
function makeRoom(playerCount){const server=new RoomServer({rng:()=>.123456});const host=server.createRoom('Host');for(let i=1;i<=playerCount;i++)server.joinRoom(host.code,`Player ${i}`);server.startGame(host.code);return{server,room:server.getRoom(host.code)}}
test('2 through 6 actual players start with valid hands and shared turn order',()=>{for(let count=2;count<=6;count++){const{room}=makeRoom(count);assert.equal(room.game.players.length,count);assert.ok(room.game.players.every(p=>p.hand.length===engine.STARTING_HAND));assert.equal(room.game.round,1);assert.equal(room.game.direction,1);assert.equal(room.players.size,count)}});
test('server rejects an invalid action from the wrong player',()=>{const{room}=makeRoom(6);const p=room.game.players[1];const before=p.hand.length;assert.throws(()=>executeGameAction(room,p.id,{type:'DRAW'}),/not.*turn/i);assert.equal(p.hand.length,before)});
test('all nine wheel slots are reachable from server RNG',()=>{for(let i=0;i<9;i++){const server=new RoomServer({rng:()=>i/9+0.00001});const host=server.createRoom('Host');server.joinRoom(host.code,'P1');server.joinRoom(host.code,'P2');server.startGame(host.code);const room=server.getRoom(host.code),g=room.game;g.turnIndex=0;g.discard=[{type:'CHARACTER',color:'red',character:'Bug'}];g.players[0].hand=[{type:engine.SPECIAL,color:null,action:engine.SPECIAL}];executeGameAction(room,g.players[0].id,{type:'PLAY_CARD',handIndex:0});const r=executeGameAction(room,g.players[0].id,{type:'SPIN_WHEEL'});assert.equal(r.character,engine.POWER_WHEEL[i].character)}});
test('2-player Reverse changes direction and advances to the other player',()=>{const{room}=makeRoom(2),g=room.game,p=g.players[0];g.turnIndex=0;g.discard=[{type:'CHARACTER',color:'red',character:'Bug'}];p.hand=[{type:'ACTION',color:'red',action:'REVERSE'}];engine.playCard(g,p.id,0);assert.equal(g.direction,-1);assert.equal(g.turnIndex,1)});
test('Skip is blocked by Shield and consumes the Shield',()=>{const{room}=makeRoom(6),g=room.game,p0=g.players[0],p1=g.players[1];p1.shield=true;g.turnIndex=0;g.discard=[{type:'CHARACTER',color:'red',character:'Bug'}];p0.hand=[{type:'ACTION',color:'red',action:'SKIP'}];engine.playCard(g,p0.id,0);assert.equal(p1.shield,false);assert.equal(g.turnIndex,1)});
test('Round 1 final card starts Round 2 and carries points',()=>{const{room}=makeRoom(3),g=room.game,p0=g.players[0];p0.points=900;g.players[1].points=875;g.players[2].points=640;g.turnIndex=0;g.discard=[{type:'CHARACTER',color:'red',character:'Bug'}];p0.hand=[{type:'CHARACTER',color:'red',character:'Face'}];const r=executeGameAction(room,p0.id,{type:'PLAY_CARD',handIndex:0});assert.equal(g.round,2);assert.equal(g.phase,'playing');assert.equal(r.roundEnd.nextRound,2);assert.equal(g.players[0].points,1050);assert.equal(g.players[1].points,875);assert.equal(g.players[2].points,640)});
test('Round 2 final card produces the overall highest-point winner',()=>{const{room}=makeRoom(3),g=room.game,p0=g.players[0];g.round=2;p0.points=900;g.players[1].points=1200;g.players[2].points=1100;g.turnIndex=0;g.discard=[{type:'CHARACTER',color:'blue',character:'Bug'}];p0.hand=[{type:'CHARACTER',color:'blue',character:'Face'}];const result=executeGameAction(room,p0.id,{type:'PLAY_CARD',handIndex:0});assert.equal(g.phase,'finished');assert.equal(result.roundEnd.winner.id,g.players[1].id);assert.equal(g.winner.id,g.players[1].id)});
console.log('FULL GAME STRESS TESTS: PASS');
